name: meu_lar_de_volta
description: "A hopeful initiative."

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.17.3
  firebase_core: ^2.31.0
  mask_text_input_formatter: ^2.9.0
  dotlottie_loader: ^0.0.3
  lottie: ^3.1.0
  url_launcher: ^6.2.6
  flutter_spinkit: ^5.2.1
  # flutter_osm_plugin: ^1.0.3

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - lib/assets/dotlottie/

  fonts:
    - family: Bold
      fonts:
        - asset: lib/assets/fonts/Inter-Bold.ttf
    - family: Regular
      fonts:
        - asset: lib/assets/fonts/Inter-Regular.ttf
    - family: SemiBold
      fonts:
        - asset: lib/assets/fonts/Inter-SemiBold.ttf
